[project]
name = "debgraph"
version = "0.2.0"
description = "Generates a graph of your debian packages"
requires-python = ">=3.7"
dependencies = ["graphviz"]
license = "GPL-3.0-only"
license-files = [ "LICENSE", "COPYING" ]
readme = { file = "README", content-type = "text/plain" }

[project.urls]
Homepage = "https://github.com/garyg1/debgraph"
Issues = "https://github.com/garyg1/debgraph/issues"

[project.scripts]
debgraph = "debgraph.debgraph:main"

[project.optional-dependencies]
tests = ["pytest", "black"]